import { useAuth } from '../context/AuthContext';

export default function PrintTemplate({ bill, patient }) {
  const { clinic } = useAuth();

  if (!bill || !patient || !clinic) return null;

  return (
    <div className="w-full text-black p-4 bg-white" style={{ fontFamily: 'sans-serif' }}>
      
      {/* Header */}
      <div className="text-center border-b-2 border-black pb-4 mb-4">
        <h1 className="text-2xl font-bold uppercase">{clinic.clinicName}</h1>
        <p className="font-semibold text-lg">{clinic.doctorName}</p>
        <p className="text-sm">{clinic.address}</p>
        <p className="text-sm">Phone: {clinic.phone} | Reg No: {clinic.registrationNumber}</p>
      </div>

      {/* Patient Details */}
      <div className="flex justify-between text-sm mb-6 border-b border-gray-300 pb-4">
        <div>
          <p><span className="font-semibold">Patient Name:</span> {patient.name}</p>
          <p><span className="font-semibold">Age/Gender:</span> {patient.age} / {patient.gender}</p>
          <p><span className="font-semibold">Address:</span> {patient.address}</p>
        </div>
        <div className="text-right">
          <p><span className="font-semibold">Date:</span> {new Date(bill.date).toLocaleDateString()}</p>
          <p><span className="font-semibold">Bill No:</span> {bill._id.slice(-6).toUpperCase()}</p>
        </div>
      </div>

      {/* Prescription & Bill Items */}
      <table className="w-full text-sm text-left mb-6 border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="py-2">S.No</th>
            <th className="py-2">Medicine / Item</th>
            <th className="py-2 text-center">Qty</th>
            <th className="py-2 text-right">Unit Price</th>
            <th className="py-2 text-right">Total</th>
          </tr>
        </thead>
        <tbody>
          {bill.items.map((item, idx) => (
            <tr key={idx} className="border-b border-gray-200">
              <td className="py-2">{idx + 1}</td>
              <td className="py-2 font-semibold">{item.name}</td>
              <td className="py-2 text-center">{item.qty}</td>
              <td className="py-2 text-right">₹{item.unitPrice.toFixed(2)}</td>
              <td className="py-2 text-right">₹{item.total.toFixed(2)}</td>
            </tr>
          ))}
          {/* Consultation Fee */}
          <tr className="border-b border-gray-200">
            <td className="py-2"></td>
            <td className="py-2 font-semibold">Doctor Consultation Fee</td>
            <td className="py-2 text-center">1</td>
            <td className="py-2 text-right">₹{bill.consultationFee.toFixed(2)}</td>
            <td className="py-2 text-right">₹{bill.consultationFee.toFixed(2)}</td>
          </tr>
        </tbody>
      </table>

      {/* Totals & QR */}
      <div className="flex justify-between items-end mt-8">
        <div className="text-center">
          {bill.qrCodeUrl && (
            <>
              <img src={bill.qrCodeUrl} alt="UPI QR Code" className="w-32 h-32 mx-auto" />
              <p className="text-xs font-semibold mt-1">Scan to Pay via UPI</p>
              <p className="text-xs">{clinic.upiId}</p>
            </>
          )}
        </div>
        <div className="text-right">
          <p className="text-2xl font-bold">Grand Total: ₹{bill.grandTotal.toFixed(2)}</p>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-16 flex justify-between items-end border-t border-gray-300 pt-4 text-sm">
        <p>Generated by LukBill</p>
        <div className="text-center">
          <div className="border-b border-black w-40 mb-1"></div>
          <p>Doctor's Signature</p>
        </div>
      </div>

    </div>
  );
}
